### ISSUE TITLE
Monitoring tab disappears if there are no monitors

### ISSUE THREAD

**Issue by ankitgin** [opendistro-for-elasticsearch/alerting-kibana-plugin#25] opened 2019-04-04 13:41 UTC
If you open 
Alerting tab -> "Monitors" section

For the first time (no monitors have been created yet) the Alerting tab disappears and I can see the following error in my browser console:

manifest.json:1 Manifest: Line: 1, column: 1, Unexpected token.
vendors.bundle.js:70 TypeError: Cannot read property 'length' of undefined
    at EuiBasicTable.value (opendistro-alerting.bundle.js:6)
    at EuiBasicTable.value (opendistro-alerting.bundle.js:6)
    at EuiBasicTable.value (opendistro-alerting.bundle.js:6)

After creating a monitor, I can see the "Monitors" section. Looks like the 'length' has been updated after creating a monitor, and now even if I delete the monitor, the "Monitors" section is visible (as should be in the first place).

**Comment by dbbaughe** [comment] 2019-04-05 18:20
Hi ankitgin,

We are not able to reproduce this. Is this something you are able to reproduce?
If so can you provide a screenshot and possibly more steps so that we can see the issue.

Thanks

**Comment by ankitgin** [comment] 2019-04-05 18:33
Hi dbbaughe

Please find the attached gif files.
I have tested this in Amazon Elasticsearch in us-east-1 region.

before_creating_first_monitor gif shows the issues.

After creating a monitor we can see that the "Monitors" section is available as it should have been in the first place.

Thank you.

![before_creating_first_monitor](https://user-images.githubusercontent.com/16332442/55648810-ebbf4000-57fe-11e9-99b0-698d8ca3c1b5.gif)

![creating_first_monitor](https://user-images.githubusercontent.com/16332442/55648981-596b6c00-57ff-11e9-81df-47d1129035af.gif)

**Comment by mihirsoni** [comment] 2019-04-05 20:04
Hi @ankitgin 

Thanks for providing us steps for reproduce this bug. 

We're working on the fix.

**Comment by mihirsoni** [comment] 2019-05-15 17:52
This is not related to OD , so closing this for now.

**Closed by mihirsoni** 2019-05-15 17:52 UTC
